import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home({ posts }) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>Blog page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web development, programming" />
      </Head>
      <main className={styles.container}>
        <h2>This is Compact blog  home page</h2>
        <h3>More update comming soon......</h3>
        <p>lorem12 </p>
      </main>

    </>
  )
}

// export const getStaticProps = async () => {
//   const res = await fetch('https://jsonplaceholder.typicode.com/users')
//   const data = await res.json(JSON.stringify(data))

//   return {
//     props: { posts: data }
//   }
// }