import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Navbar from '../components/Shared/Navbar';
import Banner from '../components/home/Banner';
import Services from '../components/home/Services';
import Projects from '../components/home/Projects';
import WhyYouChooseUs from '../components/home/whyYouChooseUs';
import Contact from '../components/home/Contact';
import ScrollToTop from 'react-scroll-to-top';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAngleUp } from '@fortawesome/free-solid-svg-icons';
import Footer from '../components/Shared/Footer';

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Blog page</title>
        <link href={`https://api.fontshare.com/css?f[]=general-sans@200,201,300,400,401,500,600,700&display=swap`} rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        {/* <script src="https://kit.fontawesome.com/acc18e30fe.js" crossOrigin="anonymous"></script> */}
        <link rel="stylesheet" href="css/izmir.min.css" />
        <meta name="keywords" content="web development, programming" />
      </Head>
      <main className={styles.container}>
        <div className={`${styles.banner}`}>
          <Navbar />
          <Banner />
        </div>
        <Services />
        <Projects />
        <WhyYouChooseUs />
        <Contact />
        <ScrollToTop smooth component={<FontAwesomeIcon style={{ fontSize: '25px' }} icon={faAngleUp} />} style={{ background: 'white', borderRadius: '50%', color: 'black' }} />
      </main>
      <Footer />
    </>
  )
}

// export const getStaticProps = async () => {
//   const res = await fetch('https://jsonplaceholder.typicode.com/users')
//   const data = await res.json(JSON.stringify(data))

//   return {
//     props: { posts: data }
//   }
// }