import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home({ posts }) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>Exploring Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web development, programming" />
      </Head>
      <main className={styles.container}>
        <h1>{posts.length}</h1>
        {
          posts.map((post) => (
            <div key={post.id} className={styles.card}>
              <h2>{post.name}</h2>
              <h4> Email :{post.email}</h4>
              <h4> Website :{post.website}</h4>
              <Link key={post.id} href={`/user/${post.id}`}>
                <button>More Details</button>
              </Link>
            </div>
          ))
        }
      </main>

    </>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const data = await res.json()

  return {
    props: { posts: data }
  }
}